name: NodeJs Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  sonarqube_sast_scan:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job runs first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Keep this if you need full git history for SonarQube

      - name: SonarQube Scan # make sure sonar-project.properties is present at root of the project
        uses: sonarsource/sonarqube-scan-action@v2  # Use stable version
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  snyk_sca_scan:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job runs first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Snyk Authentication
        uses: snyk/actions/node@master
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk SCA (Software Composition Analysis)
        run: snyk test --all-projects --json > snyk-report.json  # Output the Snyk report to a file
  
      - name: Commit and push Snyk report to repository
        run: |
            git config --global user.name "mani1765"
            git config --global user.email "gmanikanta.0528@gmail.com"
            git checkout -b snyk-report
            mkdir -p snyk-reports
            mv snyk-report.json snyk-reports/
            git add snyk-reports/snyk-report.json
            git commit -m "Add Snyk vulnerability report"
            git push --set-upstream origin snyk-report
  
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Used for pushing the r     
       
